# Tests using REST Client

# @server = http://localhost:5000
@server = http://localhost:3000

###
//GET {{server}}/ledger
###
GET {{server}}/?command=b gratis
###
GET {{server}}/?command=b N26
### 
# Shutdown the server
GET {{server}}/shutdown
###
# error
GET {{server}}/?command=b --flat --empty --no-total
